[-bug] Sympa SOAP server would crash when using AuthenticateRemoteAppAndrun because it tried to join an undefined reference to an array for logging purpose (this sub has no parameters). Fixed by making logs conditional.
git-svn-id: https://subversion.renater.fr/sympa/branches/sympa-6.2-branch@11757 05aa8bb8-cd2b-0410-b1d7-8918dfa770ce